source "$(dirname "$0")/loader.sh"
source "$(dirname "$0")/bookmark.sh"
source "$(dirname "$0")/brew.sh"
source "$(dirname "$0")/plugins.sh"
source "$(dirname "$0")/key.sh"
source "$(dirname "$0")/git.sh"
source "$(dirname "$0")/telegram.sh"
source "$(dirname "$0")/ssh.sh"
